"""
Sub-1 Perception — validation test.

Runs the Tracker against a set of synthetic frames and checks that:
  1. Tracking continuity > 70 % of frames exceed CONFIDENCE_THRESH.
  2. Position MAE < 0.15 m vs ground-truth offsets.

Synthetic frames are generated by rendering a filled red circle of known
radius onto a black canvas at a known position — no PyBullet required.

Usage:
    python sub1_perception/test_perception.py
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import numpy as np
import cv2

from sub1_perception.distance_estimator import DistanceEstimator
from sub1_perception.tracker import Tracker, CONFIDENCE_THRESH, CAMERA_RES, CAMERA_FOV, MARKER_WIDTH_M

# ── Test configuration ────────────────────────────────────────────────────────
NUM_FRAMES = 200          # Total synthetic frames to generate
OCCLUSION_RATE = 0.05     # Fraction of frames where marker is hidden

# Ground-truth offsets to simulate (drone hovering 2 m above, marker shifting)
GT_DX_RANGE = (-1.0, 1.0)   # metres
GT_DY_RANGE = (-1.0, 1.0)
GT_DZ = 2.0                  # Fixed altitude above user

PASS_CONTINUITY = 0.70   # Minimum fraction of frames with confidence > thresh
PASS_MAE_M = 0.15        # Maximum mean absolute error in metres
# ─────────────────────────────────────────────────────────────────────────────


def render_frame(cx_px: int, cy_px: int, radius_px: int) -> np.ndarray:
    """Draw a solid red circle on a black frame (RGB)."""
    W, H = CAMERA_RES
    frame = np.zeros((H, W, 3), dtype=np.uint8)
    cv2.circle(frame, (cx_px, cy_px), radius_px, (220, 30, 30), thickness=-1)
    return frame


def gt_to_pixels(dx_m: float, dy_m: float, dz_m: float) -> tuple:
    """Convert ground-truth body-frame offset to expected pixel centroid."""
    estimator = DistanceEstimator()
    f = estimator.focal_length_px(CAMERA_RES[0], CAMERA_FOV)
    W, H = CAMERA_RES
    cx = int(W / 2 + dx_m * f / dz_m)
    cy = int(H / 2 - dy_m * f / dz_m)
    # Apparent width of marker at this distance
    radius_px = max(1, int((MARKER_WIDTH_M * f / dz_m) / 2))
    return cx, cy, radius_px


def run_tests():
    estimator = DistanceEstimator()
    tracker = Tracker(estimator)

    rng = np.random.default_rng(42)

    # Slow sinusoidal walk — EMA is designed for smooth trajectories, not random jumps.
    # Amplitude capped at 0.5 m so the marker stays fully inside the camera frame
    # at GT_DZ = 2.0 m (image half-height covers ≈ 0.87 m at that altitude).
    t = np.linspace(0, 4 * np.pi, NUM_FRAMES)
    gt_dx_values = np.sin(t) * 0.5        # ±0.5 m lateral oscillation
    gt_dy_values = np.cos(t * 0.7) * 0.5  # ±0.5 m fore/aft at different rate
    occluded = rng.random(NUM_FRAMES) < OCCLUSION_RATE

    errors = []
    confident_frames = 0

    for i in range(NUM_FRAMES):
        dx_gt = float(gt_dx_values[i])
        dy_gt = float(gt_dy_values[i])

        if occluded[i]:
            # Blank frame — no marker visible
            frame = np.zeros((CAMERA_RES[1], CAMERA_RES[0], 3), dtype=np.uint8)
        else:
            cx_px, cy_px, radius_px = gt_to_pixels(dx_gt, dy_gt, GT_DZ)
            frame = render_frame(cx_px, cy_px, radius_px)

        pos, conf = tracker.process_frame(frame)

        if conf >= CONFIDENCE_THRESH:
            confident_frames += 1
            err = np.sqrt((pos[0] - dx_gt) ** 2 + (pos[1] - dy_gt) ** 2)
            errors.append(err)

    continuity = confident_frames / NUM_FRAMES
    mae = float(np.mean(errors)) if errors else float("inf")

    print(f"Tracking continuity : {continuity:.2%}  (target > {PASS_CONTINUITY:.0%})")
    print(f"Position MAE        : {mae:.4f} m  (target < {PASS_MAE_M} m)")

    pass_continuity = continuity > PASS_CONTINUITY
    pass_mae = mae < PASS_MAE_M

    if pass_continuity and pass_mae:
        print("\nSub-1 PASSED all checks.")
        return 0
    else:
        print("\nSub-1 FAILED:")
        if not pass_continuity:
            print(f"  Continuity {continuity:.2%} <= {PASS_CONTINUITY:.0%}")
        if not pass_mae:
            print(f"  MAE {mae:.4f} m >= {PASS_MAE_M} m")
        return 1


if __name__ == "__main__":
    sys.exit(run_tests())
